language: c
os:
    - osx
    - linux
env:
    matrix:
        - TOXENV=py26
        - TOXENV=py27
        - TOXENV=py32
        - TOXENV=py33
        - TOXENV=py34
        - TOXENV=pypy
        - TOXENV=py26 OPENSSL=0.9.8
        - TOXENV=py27 OPENSSL=0.9.8
        - TOXENV=py32 OPENSSL=0.9.8
        - TOXENV=py33 OPENSSL=0.9.8
        - TOXENV=py34 OPENSSL=0.9.8
        - TOXENV=pypy OPENSSL=0.9.8
        - TOXENV=docs
        - TOXENV=pep8
        - TOXENV=py3pep8

install:
    - ./.travis/install.sh

script:
    - ./.travis/run.sh

after_success:
    - source ~/.venv/bin/activate && coveralls
